Repository busybee23/Hacktoberfest-2021, pull requests merged in 2021-10, with the labels that each got.

#3 Update Bella Ciao (CHFHEIST).md
  Codechef/DIV 3/LONG CHALLENGE/JUNE CHALLENGE 2021/Bella Ciao (CHFHEIST).md
Labels: hactoberfest2021

#2 Create stringinJava
  GeeksForGeeks/String/stringinJava
Labels: hactoberfest2021

#4 Update GettingStarted.js
  DEV/Java Script/GettingStarted.js
Labels: hactoberfest2021, hactoberfest-accepted

#6 Update README.md
  README.md
Labels: hactoberfest-accepted

#11 Create average.cpp
  QUICK-CODE/average.cpp
Labels: hactoberfest2021, hactoberfest-accepted

#10 stack implementation java file added
  GeeksForGeeks/FAMOUS ALGORITHMS/SORT/SelectionSort.java
  GeeksForGeeks/Stack/Easy/Stack.java
Labels: hactoberfest2021, hactoberfest-accepted

#12 Create Arraysum.cpp
  C++/Arraysum.cpp
Labels: hactoberfest2021, hactoberfest-accepted

#14 Create Make the String Great.cpp
  LEET-CODE/EASY/STRING/Make the String Great.cpp
Labels: hactoberfest2021, hactoberfest-accepted

#13 Added to new files
  C++/Factorial.cpp
  C++/FibonaciSeries.cpp
Labels: hactoberfest2021, hactoberfest-accepted

#15 Have added Maximum Subarray Problem's solution from leetcode.
  LEET-CODE/EASY/ARRAY/#53. Maximum Subarray.md
Labels: hactoberfest2021, hactoberfest-accepted

#18 factorial_by_recursion
  QUICK-CODE/factorial_by_recursion
Labels: hactoberfest2021, hactoberfest-accepted

#17 Added RangQuery program in cpp
  C++/RangeQuery.cpp
Labels: hactoberfest2021, hactoberfest-accepted

#16 Two Basic and Important types of question Added
  C++/QuadraticEqnRoots.cpp
  C++/Sumof_n_naturalnumbers.cpp
Labels: hactoberfest2021, hactoberfest-accepted

#22 Added Java Programs
  Java/Account.java
  Java/Calculator.java
  Java/Data Structure/LinkedList.java
  Java/GenericSort.java
  Java/NQueens.java
  Java/QueueExample.java
  Java/SimpleQueue.java
  Java/Sorting Algorithms/.vscode/settings.json
  Java/Sorting Algorithms/Bubble Sort/All About Bubble Sort.txt.rtf
  Java/Sorting Algorithms/Bubble Sort/bubbleSort.java
  Java/Sorting Algorithms/Insertion Sort/All about insertion sort.rtf
  Java/Sorting Algorithms/Insertion Sort/insertionSort.java
  Java/Sorting Algorithms/Merge Sort/All about Merge Sort.rtf
  Java/Sorting Algorithms/Merge Sort/mergeSort.java
  Java/Sorting Algorithms/Quick Sort/All about Quick Sort.rtf
  Java/Sorting Algorithms/Quick Sort/quickSort.java
  Java/Sorting Algorithms/Selection Sort/All About Selection Sort.rtf
  Java/Sorting Algorithms/Selection Sort/selectionSort.java
  Java/oldMan.java
  Java/towerofhanoi.java
Labels: hacktoberfest2021, hacktoberfest-accepted

#24 Added a program to Find GCD/HCF of two Numbers
  C++/FindGCD.cpp
Labels: hacktoberfest2021, hacktoberfest-accepted

#23 Understanding variable arguments in java
  QUICK-CODE/Recap/VarArgs.java
Labels: hacktoberfest2021, hacktoberfest-accepted

#126 Added an Age calculator and a Number Conversion System
  C/Number-System-Conversion.c
  DEV/Java Script/Age-calculator/Age-Calculator.css
  DEV/Java Script/Age-calculator/Age-Calculator.html
  DEV/Java Script/Age-calculator/Age-Calculator.js
Labels: hacktoberfest2021, hacktoberfest-accepted
